name:                parskell
version:             0.1.0.0
github:              "nomis6432/parskell"
license:             BSD3
author:              "Simon Tas"
maintainer:          "simon.tas.st@gmail.com"
copyright:           "2021 Simon Tas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nomis6432/parskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- syntactic >= 3.8

library:
  source-dirs: src

executables:
  parskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parskell

tests:
  parskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parskell
